version: '3.8'
services:
  client:
    build: ./client
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
    command: npm start
    depends_on:
      - server
  server:
    build: ./server
    ports:
      - '8000:8000'
    volumes:
      - ./server:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data: